orbs: # declare what orbs we are going to use
  node: circleci/node@12.18.3 # the node orb provides common node-related configuration

version: 2.1 # using 2.1 provides access to orbs and other features

jobs:
  build:
    docker:
      - image: circleci/node@12.18.3
    steps:
      - checkout
      - run: npm install --save
      - run: npm test

workflows:
  matrix-tests:
    jobs:
      - node/test:
          version: 12.18.3
